import { useEffect, useMemo, useState } from "react";
import {
  ArrowsClockwise, ArrowsLeftRight, Bell, Camera, CaretRight, ChartBar, Check, CheckCircle, ClipboardText, Clock, Cube,
  DownloadSimple, Factory, Gear, List, ListChecks, MagnifyingGlass, MapPin, PaperPlaneTilt, Play, QrCode, Scan,
  ShieldCheck, Timer, UploadSimple, User, UserPlus, UsersThree, WarningCircle, Wrench, XCircle,
} from "@phosphor-icons/react";
import { copy } from "./i18n.js";

const STORAGE_KEY = "m4-workflow-v5";
const WAIT_LIMIT_MS = 10 * 60 * 1000;
const REPAIR_LIMIT_MS = 15 * 60 * 1000;
const ACCEPT_LIMIT_MS = 20 * 60 * 1000;
const featureCopy = {
  zh:{navExceptions:"异常中心",exceptionCenterTitle:"维修异常中心",exceptionCenterSub:"优先处理超时、无人接单和疑似重复故障",urgentTotal:"需立即处理",noClaim:"无人接单",repairOverdue:"维修超时",acceptanceOverdue:"待验收超时",repeatSuspected:"疑似重复故障",exceptionFor:"已持续",slaClaim:"接单时限",slaRepair:"维修时限",slaAcceptance:"验收时限",overdueBy:"已超时",withinSla:"SLA 正常",waitingClaimStep:"等待接单",openDuration:"工单已持续",closedTotalTime:"闭环总耗时",siteEvidence:"现场证据",reportPhotos:"报修照片",recentMaintenance:"该设备近期维修",adminFallback:"管理员兜底指派",viewEquipmentRecord:"查看设备档案",exceptionAlert:"任务已超过处理时限，建议立即介入，避免影响产线。",chooseTechnician:"选择接手工程师",records:"条记录",repeatHint:"7 天内出现同类故障，建议核对历史维修结论。",noException:"当前没有需要介入的异常",claimRule:"超过 10 分钟无人接单",repairRule:"维修用时超过 15 分钟",acceptanceRule:"维修完成后 20 分钟未验收",repeatRule:"7 天内同设备同类故障再次发生"},
  en:{navExceptions:"Exception center",exceptionCenterTitle:"Maintenance exception center",exceptionCenterSub:"Prioritize overdue, unclaimed and suspected repeat faults",urgentTotal:"Needs action",noClaim:"Unclaimed",repairOverdue:"Repair overdue",acceptanceOverdue:"Acceptance overdue",repeatSuspected:"Repeat suspected",exceptionFor:"Open for",slaClaim:"Claim SLA",slaRepair:"Repair SLA",slaAcceptance:"Acceptance SLA",overdueBy:"Overdue",withinSla:"Within SLA",waitingClaimStep:"Waiting for claim",openDuration:"Order open",closedTotalTime:"Total closure time",siteEvidence:"Site evidence",reportPhotos:"Report photos",recentMaintenance:"Recent maintenance on this equipment",adminFallback:"Admin fallback assignment",viewEquipmentRecord:"View equipment record",exceptionAlert:"This task is beyond its response target. Intervene now to protect line output.",chooseTechnician:"Choose a technician",records:"records",repeatHint:"The same fault recurred within 7 days. Review the previous repair conclusion.",noException:"No exceptions need intervention",claimRule:"Unclaimed for more than 10 minutes",repairRule:"Repair active for more than 15 minutes",acceptanceRule:"Awaiting acceptance for more than 20 minutes",repeatRule:"Same equipment and fault recurred within 7 days"},
  bm:{navExceptions:"Pusat pengecualian",exceptionCenterTitle:"Pusat pengecualian penyelenggaraan",exceptionCenterSub:"Utamakan tugas lewat, belum diterima dan kerosakan berulang",urgentTotal:"Perlu tindakan",noClaim:"Belum diterima",repairOverdue:"Baiki lewat",acceptanceOverdue:"Pengesahan lewat",repeatSuspected:"Disyaki berulang",exceptionFor:"Berlangsung",slaClaim:"SLA terima",slaRepair:"SLA baiki",slaAcceptance:"SLA pengesahan",overdueBy:"Lewat",withinSla:"Dalam SLA",waitingClaimStep:"Menunggu diterima",openDuration:"Tiket terbuka",closedTotalTime:"Jumlah masa tutup",siteEvidence:"Bukti lokasi",reportPhotos:"Gambar laporan",recentMaintenance:"Penyelenggaraan mesin terkini",adminFallback:"Penugasan sandaran pentadbir",viewEquipmentRecord:"Lihat rekod mesin",exceptionAlert:"Tugas melebihi sasaran masa. Campur tangan sekarang untuk melindungi output barisan.",chooseTechnician:"Pilih juruteknik",records:"rekod",repeatHint:"Kerosakan sama berulang dalam 7 hari. Semak kesimpulan pembaikan terdahulu.",noException:"Tiada pengecualian perlu tindakan",claimRule:"Belum diterima lebih 10 minit",repairRule:"Pembaikan lebih 15 minit",acceptanceRule:"Menunggu pengesahan lebih 20 minit",repeatRule:"Mesin dan kerosakan sama berulang dalam 7 hari"}
};
Object.entries(featureCopy).forEach(([lang,labels])=>Object.assign(copy[lang],labels));
const actionCopy={
  zh:{menu:"菜单",closeMenu:"关闭菜单",quickActions:"当前操作",reportProblem:"报错",problemReported:"问题已记录，管理员可在工单记录中查看",eventProblem:"已上报处理异常",finishAction:"完成维修",cancelDraft:"取消",draftCleared:"本次报修内容已清空",refreshData:"刷新",refreshDone:"已刷新到最新数据",selectOrderFirst:"请先选择一张工单",viewExceptionStatus:"查看异常维修状态"},
  en:{menu:"Menu",closeMenu:"Close menu",quickActions:"Current actions",reportProblem:"Report issue",problemReported:"Issue recorded in the work order for admin review",eventProblem:"reported a handling issue",finishAction:"Finish repair",cancelDraft:"Cancel",draftCleared:"This repair report draft has been cleared",refreshData:"Refresh",refreshDone:"Latest data loaded",selectOrderFirst:"Select a work order first",viewExceptionStatus:"View exception status"},
  bm:{menu:"Menu",closeMenu:"Tutup menu",quickActions:"Tindakan semasa",reportProblem:"Lapor masalah",problemReported:"Masalah direkodkan dalam tiket untuk semakan pentadbir",eventProblem:"melaporkan masalah pengendalian",finishAction:"Selesai baiki",cancelDraft:"Batal",draftCleared:"Draf laporan pembaikan telah dikosongkan",refreshData:"Muat semula",refreshDone:"Data terkini dimuatkan",selectOrderFirst:"Pilih tiket dahulu",viewExceptionStatus:"Lihat status pengecualian"}
};
Object.entries(actionCopy).forEach(([lang,labels])=>Object.assign(copy[lang],labels));
const machines = [
  { id:"M-12", nameKey:"pressMachine", line:"Line 2", station:"A-04" },
  { id:"M-03", nameKey:"motorStation", line:"Line 1", station:"B-11" },
  { id:"M-08", nameKey:"sensorStation", line:"Line 3", station:"C-02" },
  { id:"M-17", nameKey:"packingMachine", line:"Line 1", station:"B-08" },
];
const faults = ["cannotStart","abnormalNoise","sensorFault","qualityIssue","otherFault"];
const causes = ["electrical","mechanical","sensor","adjustment"];
const technicians = [
  { name:"Azlan", avatar:"/assets/avatar-azlan.png" },
  { name:"Mei Ling", avatar:"/assets/avatar-mei-ling.png" },
  { name:"Kumar", avatar:"/assets/avatar-kumar.png" },
];

function seedTasks(base=Date.now()) {
  return [
    { id:"WO-260824-01",machineId:"M-12",machineKey:"pressMachine",issueKey:"cannotStart",status:"reported",reporter:"Lim Wei",location:"Line 2 · A-04",reportedAt:base-24*60_000,photo:"/assets/report-m12-connector.png",photos:["/assets/report-m12-connector.png","/assets/report-m12-drive.png"],note:"主驱动无法启动，复位后仍无反应。" },
    { id:"WO-260824-02",machineId:"M-03",machineKey:"motorStation",issueKey:"abnormalNoise",status:"repairing",reporter:"Nur Aina",location:"Line 1 · B-11",assignee:"Azlan",avatar:technicians[0].avatar,reportedAt:base-40*60_000,acceptedAt:base-37*60_000,repairStartedAt:base-21*60_000,photo:"/assets/report-m12-drive.png",photos:["/assets/report-m12-drive.png"],note:"高速运行时出现间歇性金属摩擦声。" },
    { id:"WO-260824-03",machineId:"M-08",machineKey:"sensorStation",issueKey:"sensorFault",status:"acceptance",reporter:"Lim Wei",location:"Line 3 · C-02",assignee:"Mei Ling",avatar:technicians[1].avatar,reportedAt:base-58*60_000,acceptedAt:base-54*60_000,repairStartedAt:base-48*60_000,repairCompletedAt:base-26*60_000,result:{causeKey:"sensor",note:"Sensor connector cleaned and signal tested.",photo:"/assets/report-m12-connector.png",photos:["/assets/report-m12-connector.png"]},photo:"/assets/report-m12-drive.png",photos:["/assets/report-m12-drive.png"],note:"传感器读数不稳定，设备自动停机。" },
    { id:"WO-260824-04",machineId:"M-17",machineKey:"packingMachine",issueKey:"qualityIssue",status:"repairing",reporter:"Siti Hana",location:"Line 1 · B-08",assignee:"Kumar",avatar:technicians[2].avatar,reportedAt:base-24*60_000,acceptedAt:base-21*60_000,repairStartedAt:base-18*60_000,repeatSuspected:true,photo:"/assets/report-m12-connector.png",photos:["/assets/report-m12-connector.png"],note:"封口偏移，本周第二次出现相同问题。" },
    { id:"WO-260823-05",machineId:"M-12",machineKey:"pressMachine",issueKey:"abnormalNoise",status:"closed",reporter:"Lim Wei",location:"Line 2 · A-04",assignee:"Azlan",avatar:technicians[0].avatar,reportedAt:base-1*86_400_000,acceptedAt:base-1*86_400_000+6*60_000,repairStartedAt:base-1*86_400_000+9*60_000,repairCompletedAt:base-1*86_400_000+31*60_000,closedAt:base-1*86_400_000+36*60_000,result:{causeKey:"mechanical",note:"Bearing alignment corrected and tested.",photo:""},photo:"",note:"" },
    { id:"WO-260821-06",machineId:"M-03",machineKey:"motorStation",issueKey:"cannotStart",status:"closed",reporter:"Nur Aina",location:"Line 1 · B-11",assignee:"Mei Ling",avatar:technicians[1].avatar,reportedAt:base-3*86_400_000,acceptedAt:base-3*86_400_000+4*60_000,repairStartedAt:base-3*86_400_000+7*60_000,repairCompletedAt:base-3*86_400_000+25*60_000,closedAt:base-3*86_400_000+29*60_000,result:{causeKey:"electrical",note:"Starter relay replaced and current checked.",photo:""},photo:"",note:"" },
    { id:"WO-260818-07",machineId:"M-08",machineKey:"sensorStation",issueKey:"sensorFault",status:"closed",reporter:"Chen Hao",location:"Line 3 · C-02",assignee:"Kumar",avatar:technicians[2].avatar,reportedAt:base-6*86_400_000,acceptedAt:base-6*86_400_000+9*60_000,repairStartedAt:base-6*86_400_000+12*60_000,repairCompletedAt:base-6*86_400_000+41*60_000,closedAt:base-6*86_400_000+47*60_000,result:{causeKey:"sensor",note:"Proximity sensor replaced and calibrated.",photo:""},photo:"",note:"" },
    { id:"WO-260810-08",machineId:"M-17",machineKey:"packingMachine",issueKey:"qualityIssue",status:"closed",reporter:"Siti Hana",location:"Line 1 · B-08",assignee:"Azlan",avatar:technicians[0].avatar,reportedAt:base-14*86_400_000,acceptedAt:base-14*86_400_000+5*60_000,repairStartedAt:base-14*86_400_000+8*60_000,repairCompletedAt:base-14*86_400_000+20*60_000,closedAt:base-14*86_400_000+24*60_000,result:{causeKey:"adjustment",note:"Seal temperature and guide pressure adjusted.",photo:""},photo:"",note:"" },
    { id:"WO-260730-09",machineId:"M-12",machineKey:"pressMachine",issueKey:"cannotStart",status:"closed",reporter:"Lim Wei",location:"Line 2 · A-04",assignee:"Mei Ling",avatar:technicians[1].avatar,reportedAt:base-25*86_400_000,acceptedAt:base-25*86_400_000+7*60_000,repairStartedAt:base-25*86_400_000+10*60_000,repairCompletedAt:base-25*86_400_000+44*60_000,closedAt:base-25*86_400_000+50*60_000,result:{causeKey:"electrical",note:"Safety interlock circuit repaired.",photo:""},photo:"",note:"" },
  ];
}
function readTasks(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(data)&&data.length?data:seedTasks();}catch{return seedTasks();}}
function clock(value,lang){if(!value)return "—";return new Intl.DateTimeFormat(lang==="zh"?"zh-CN":lang==="bm"?"ms-MY":"en-MY",{hour:"2-digit",minute:"2-digit"}).format(value);}
function clockWithSeconds(value,lang){if(!value)return "—";return new Intl.DateTimeFormat(lang==="zh"?"zh-CN":lang==="bm"?"ms-MY":"en-MY",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(value);}
function duration(start,end,lang){if(!start)return "—";const seconds=Math.max(0,Math.floor(((end||Date.now())-start)/1000));const mins=Math.floor(seconds/60);const secs=seconds%60;return lang==="zh"?`${mins}分 ${secs}秒`:`${mins}m ${secs}s`;}
function relativeTime(value,now,lang){if(!value)return "—";const seconds=Math.max(0,Math.floor((now-value)/1000));if(seconds<60)return lang==="zh"?`${seconds}秒前`:lang==="bm"?`${seconds}s lalu`:`${seconds}s ago`;const minutes=Math.floor(seconds/60),remain=seconds%60;if(minutes<60)return lang==="zh"?`${minutes}分${remain?`${remain}秒`:""}前`:lang==="bm"?`${minutes}m lalu`:`${minutes}m ago`;const hours=Math.floor(minutes/60),remainMinutes=minutes%60;if(hours<24)return lang==="zh"?`${hours}小时${remainMinutes?`${remainMinutes}分`:""}前`:lang==="bm"?`${hours}j lalu`:`${hours}h ago`;return new Intl.DateTimeFormat(lang==="zh"?"zh-CN":lang==="bm"?"ms-MY":"en-MY",{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(value);}
function minutesBetween(start,end){return start&&end?Math.max(0,(end-start)/60_000):null;}
function average(values){const valid=values.filter(value=>Number.isFinite(value));return valid.length?valid.reduce((sum,value)=>sum+value,0)/valid.length:0;}
function formatMinutes(value,lang){const rounded=Math.round(value||0);return lang==="zh"?`${rounded} 分钟`:`${rounded} min`;}
function percentage(value,total){return total?Math.round(value/total*100):0;}
function periodTasks(tasks,period,now){const days=period==="weekly"?7:30;return tasks.filter(task=>task.reportedAt>=now-days*86_400_000);}
function technicianStats(tasks){return technicians.map(tech=>{const assigned=tasks.filter(task=>task.assignee===tech.name);const completed=assigned.filter(task=>task.repairCompletedAt);return {...tech,accepted:assigned.length,completed:completed.length,active:assigned.filter(task=>["assigned","repairing"].includes(task.status)).length,avgResponse:average(assigned.map(task=>minutesBetween(task.reportedAt,task.acceptedAt))),avgRepair:average(completed.map(task=>minutesBetween(task.repairStartedAt,task.repairCompletedAt))),completion:percentage(completed.length,assigned.length)};});}
function groupedStats(tasks,keyGetter){const keys=tasks.map(keyGetter).filter(Boolean);const map=new Map();keys.forEach(key=>map.set(key,(map.get(key)||0)+1));return [...map.entries()].map(([key,count])=>({key,count,share:percentage(count,keys.length)})).sort((a,b)=>b.count-a.count);}
function statusKey(status){return {reported:"statusReported",assigned:"statusAssigned",repairing:"statusRepairing",acceptance:"statusAcceptance",closed:"statusClosed"}[status];}
function StatusIcon({status,size=18}){if(status==="reported")return <WarningCircle size={size}/>;if(status==="assigned")return <UserPlus size={size}/>;if(status==="repairing")return <Wrench size={size}/>;return <CheckCircle size={size}/>;}
function StatusBadge({task,t}){return <span className={`status-badge ${task.status}`}><StatusIcon status={task.status} size={16}/>{t(statusKey(task.status))}</span>;}

function getException(task,now){
  if(task.status==="reported"&&now-task.reportedAt>=WAIT_LIMIT_MS)return {type:"noClaim",startedAt:task.reportedAt,limit:WAIT_LIMIT_MS,rule:"claimRule",sla:"slaClaim"};
  if(task.repeatSuspected)return {type:"repeatSuspected",startedAt:task.reportedAt,limit:0,rule:"repeatRule",sla:"repeatSuspected"};
  if(task.status==="repairing"&&task.repairStartedAt&&now-task.repairStartedAt>=REPAIR_LIMIT_MS)return {type:"repairOverdue",startedAt:task.repairStartedAt,limit:REPAIR_LIMIT_MS,rule:"repairRule",sla:"slaRepair"};
  if(task.status==="acceptance"&&task.repairCompletedAt&&now-task.repairCompletedAt>=ACCEPT_LIMIT_MS)return {type:"acceptanceOverdue",startedAt:task.repairCompletedAt,limit:ACCEPT_LIMIT_MS,rule:"acceptanceRule",sla:"slaAcceptance"};
  return null;
}
function matchesExceptionType(task,type,now){if(type==="noClaim")return task.status==="reported"&&now-task.reportedAt>=WAIT_LIMIT_MS;if(type==="repairOverdue")return task.status==="repairing"&&task.repairStartedAt&&now-task.repairStartedAt>=REPAIR_LIMIT_MS;if(type==="acceptanceOverdue")return task.status==="acceptance"&&task.repairCompletedAt&&now-task.repairCompletedAt>=ACCEPT_LIMIT_MS;if(type==="repeatSuspected")return Boolean(task.repeatSuspected);return Boolean(getException(task,now));}
function evidencePhotos(task){const report=task.photos?.length?task.photos:task.photo?[task.photo]:[];const result=task.result?.photos?.length?task.result.photos:task.result?.photo?[task.result.photo]:[];return [...new Set([...report,...result])];}

function GlobalOrderSearch({tasks,role,t,onNavigate}){
  const [query,setQuery]=useState("");
  const [scope,setScope]=useState("all");
  const [open,setOpen]=useState(false);
  useEffect(()=>{setQuery("");setScope("all");setOpen(false);},[role]);
  const visible=tasks.filter(task=>role==="admin"||(role==="operator"?task.reporter==="Lim Wei":task.status==="reported"||task.assignee==="Azlan"));
  const results=visible.filter(task=>{
    const scopeMatch=scope==="all"||(scope==="history"&&task.status==="closed")||(scope==="available"&&task.status==="reported")||(scope==="progress"&&["assigned","repairing","acceptance"].includes(task.status));
    const haystack=`${task.id} ${task.machineId} ${t(task.machineKey)} ${t(task.issueKey)} ${task.reporter} ${task.assignee||""}`.toLowerCase();
    return scopeMatch&&haystack.includes(query.trim().toLowerCase());
  }).slice(0,6);
  const filters=[["all","searchAll"],["history","searchHistory"],["available","searchAvailable"],["progress","searchInProgress"]];
  return <div className={`global-order-search ${open?"open":""}`}><div className="search-input"><MagnifyingGlass size={18}/><input value={query} onFocus={()=>setOpen(true)} onChange={event=>{setQuery(event.target.value);setOpen(true);}} placeholder={t("searchPlaceholder")} aria-label={t("searchPlaceholder")}/>{query&&<button aria-label="Clear" onClick={()=>setQuery("")}><XCircle size={17}/></button>}</div>{open&&<div className="search-popover"><div className="search-scopes">{filters.map(([key,label])=><button key={key} className={scope===key?"active":""} onClick={()=>setScope(key)}>{t(label)}<span>{visible.filter(task=>key==="all"||(key==="history"&&task.status==="closed")||(key==="available"&&task.status==="reported")||(key==="progress"&&["assigned","repairing","acceptance"].includes(task.status))).length}</span></button>)}</div><div className="search-result-head"><strong>{t("searchResults")}</strong><button onClick={()=>setOpen(false)}>×</button></div><div className="search-results">{results.length?results.map(task=><button key={task.id} onClick={()=>{onNavigate(task);setOpen(false);}}><span className={`status-symbol ${task.status}`}><StatusIcon status={task.status} size={18}/></span><span><strong>{task.machineId} · {t(task.machineKey)}</strong><small>{task.id} · {t(task.issueKey)}</small></span><StatusBadge task={task} t={t}/><CaretRight size={16}/></button>):<div className="search-empty"><MagnifyingGlass size={22}/>{t("noSearchResults")}</div>}</div></div>}</div>;
}

function Header({role,setRole,lang,setLang,t,tasks,onSearchNavigate,onMenuOpen,alertCount=0}){
  const profile=role==="admin"?"Nadia":role==="operator"?"Lim Wei":"Azlan";
  const showAlert=role==="admin"&&alertCount>0;
  return <header className="topbar">
    <div className="factory-context"><button className={`mobile-menu-trigger ${showAlert?"has-alert":""}`} onClick={onMenuOpen} aria-label={showAlert?`${t("menu")} · ${alertCount} ${t("urgentTotal")}`:t("menu")}><List size={23}/><span>{t("menu")}</span>{showAlert&&<b className="menu-alert" aria-hidden="true">!</b>}</button><strong>M4</strong><span>{t("factory")}</span><i/><span>{t("shift")}</span><i/><span>07:00–19:00</span></div>
    <div className="role-switch">{[["admin","roleAdmin"],["operator","roleOperator"],["technician","roleTechnician"]].map(([key,label])=><button key={key} className={role===key?"active":""} onClick={()=>setRole(key)}>{t(label)}</button>)}</div>
    <GlobalOrderSearch tasks={tasks} role={role} t={t} onNavigate={onSearchNavigate}/>
    <div className="topbar-actions"><div className="languages">{[["bm","BM"],["zh","中文"],["en","EN"]].map(([key,label])=><button key={key} className={lang===key?"active":""} onClick={()=>setLang(key)}>{label}</button>)}</div><button className="icon-button notification" aria-label="Notifications"><Bell size={20}/><span/></button><div className="profile"><span>{profile[0]}</span><b>{profile}</b></div></div>
  </header>;
}

function TaskList({tasks,selectedId,onSelect,t,lang,now,emptyHint}){
  if(!tasks.length)return <div className="empty-state"><ClipboardText size={34}/><strong>{emptyHint||t("noOrders")}</strong><span>{t("noOrdersHint")}</span></div>;
  return <div className="task-list" role="listbox">{tasks.map(task=><button key={task.id} className={`task-row ${selectedId===task.id?"selected":""}`} onClick={()=>onSelect(task.id)} role="option" aria-selected={selectedId===task.id}><span className={`status-symbol ${task.status}`}><StatusIcon status={task.status} size={21}/></span><span className="task-copy"><strong>{task.machineId} · {t(task.machineKey)}</strong><small>{t(task.issueKey)} · {duration(task.reportedAt,task.closedAt||now,lang)}</small></span><StatusBadge task={task} t={t}/><CaretRight size={17}/></button>)}</div>;
}
function DurationStrip({task,now,t,lang}){return <div className="duration-strip"><div><Clock size={18}/><span>{t("waiting")}</span><strong>{duration(task.reportedAt,task.acceptedAt||now,lang)}</strong></div><div><Wrench size={18}/><span>{t("repairTime")}</span><strong>{task.repairStartedAt?duration(task.repairStartedAt,task.repairCompletedAt||now,lang):t("notStarted")}</strong></div><div><Timer size={18}/><span>{t(task.closedAt?"closedTotalTime":"openDuration")}</span><strong>{duration(task.reportedAt,task.closedAt||now,lang)}</strong></div></div>;}
function Timeline({task,t,lang}){const steps=[["reported",task.reportedAt],["assigned",task.acceptedAt],["repairStarted",task.repairStartedAt],["repairDone",task.repairCompletedAt],["acceptedClosed",task.closedAt]];const active=steps.findIndex(([,time])=>!time);return <ol className="timeline">{steps.map(([key,time],index)=>{const label=key==="assigned"&&!time&&index===active?"waitingClaimStep":key;return <li key={key} className={time?"complete":index===active?"active":""}><span>{time?<Check size={13} weight="bold"/>:index+1}</span><b>{t(label)}</b><small>{time?clock(time,lang):index===active?t("now"):"—"}</small></li>;})}</ol>;}

function TaskDetail({task,now,t,lang,onFallbackAssign,showFallback=true,onAccept,onReject}){
  if(!task)return <div className="detail-empty"><ListChecks size={38}/><strong>{t("orderDetail")}</strong><span>{t("selectOrder")}</span></div>;
  const overdue=task.status==="reported"&&now-task.reportedAt>=WAIT_LIMIT_MS;
  return <article className="detail-pane"><header className="detail-header"><span className="machine-block"><Factory size={31}/></span><div><div className="detail-title"><h2>{task.machineId} · {t(task.machineKey)}</h2><StatusBadge task={task} t={t}/></div><p>{task.id}</p>{task.acceptedAt&&<p className="latest-activity"><Clock size={13}/><strong>{relativeTime(task.acceptedAt,now,lang)}</strong> {task.assignee} {t("eventAccepted")}</p>}</div></header>
    <div className="fact-grid"><div><WarningCircle size={18}/><span>{t("fault")}</span><strong>{t(task.issueKey)}</strong></div><div><MapPin size={18}/><span>{t("location")}</span><strong>{task.location}</strong></div><div><User size={18}/><span>{t("reporter")}</span><strong>{task.reporter}</strong></div><div><UsersThree size={18}/><span>{t("technician")}</span><strong>{task.assignee||t("unassigned")}</strong></div></div>
    <DurationStrip task={task} now={now} t={t} lang={lang}/><Timeline task={task} t={t} lang={lang}/>
    {task.result&&<div className="result-record"><ShieldCheck size={22}/><div><strong>{t("resultRecorded")} · {t(task.result.causeKey)}</strong><p>{task.result.note}</p></div></div>}
    {showFallback&&task.status==="reported"&&<div className={`fallback-panel ${overdue?"overdue":""}`}><div>{overdue?<WarningCircle size={23}/>:<UsersThree size={23}/>}<span><strong>{overdue?t("fallbackTitle"):t("normalClaim")}</strong><small>{overdue?t("fallbackHint"):t("normalClaimHint")}</small></span></div>{overdue&&<div className="fallback-actions">{technicians.map(tech=><button key={tech.name} onClick={()=>onFallbackAssign(task.id,tech)}><img src={tech.avatar} alt=""/>{t("assign")} {tech.name}</button>)}</div>}</div>}
    {task.status==="acceptance"&&onAccept&&<div className="acceptance-box detail-acceptance"><p>{t("acceptanceHint")}</p>{task.result&&<blockquote>{task.result.note}</blockquote>}<div><button className="reject-button" onClick={()=>onReject(task.id)}><XCircle size={19}/>{t("rejectResult")}</button><button className="accept-button" onClick={()=>onAccept(task.id)}><CheckCircle size={19}/>{t("acceptResult")}</button></div></div>}
  </article>;
}

function SlaIndicator({task,now,t,lang}){
  const exception=getException(task,now);
  if(!exception)return <span className="sla-chip healthy"><CheckCircle size={16}/>{t("withinSla")}</span>;
  const elapsed=Math.max(0,now-exception.startedAt);
  const overdue=Math.max(0,elapsed-exception.limit);
  return <div className={`sla-indicator ${exception.type}`}><span><WarningCircle size={17}/><b>{t(exception.sla)}</b>{exception.limit>0&&<small>{Math.round(exception.limit/60_000)} min</small>}</span><strong>{exception.limit>0?`${t("overdueBy")} ${duration(now-overdue,now,lang)}`:t("repeatSuspected")}</strong></div>;
}

function EvidencePreview({task,t}){
  const photos=evidencePhotos(task);
  if(!photos.length&&!task.note)return null;
  return <section className="evidence-preview"><header><span><Camera size={18}/>{t("siteEvidence")}</span><b>{photos.length} {t("records")}</b></header>{task.note&&<p>{task.note}</p>}<div>{photos.map((src,index)=><figure key={`${src}-${index}`}><img src={src} alt={`${t("reportPhotos")} ${index+1}`}/><figcaption>{t("reportPhotos")} {index+1}</figcaption></figure>)}</div></section>;
}

function RecentMachineHistory({task,tasks,now,t,lang}){
  const recent=tasks.filter(item=>item.machineId===task.machineId&&item.status==="closed").sort((a,b)=>b.closedAt-a.closedAt).slice(0,2);
  if(!recent.length)return null;
  return <section className="recent-maintenance"><header><span><ArrowsClockwise size={18}/>{t("recentMaintenance")}</span><b>{recent.length}</b></header>{recent.map(item=><article key={item.id}><span className="history-dot"><Wrench size={15}/></span><div><strong>{t(item.issueKey)} · {item.result?t(item.result.causeKey):"—"}</strong><small>{item.assignee||t("unassigned")} · {relativeTime(item.closedAt,now,lang)}</small></div><b>{duration(item.reportedAt,item.closedAt,lang)}</b></article>)}</section>;
}

function ExceptionList({items,selectedId,onSelect,t,lang,now}){
  if(!items.length)return <div className="empty-state"><CheckCircle size={34}/><strong>{t("noException")}</strong></div>;
  return <div className="exception-list">{items.map(task=>{const exception=getException(task,now);return <button key={task.id} className={selectedId===task.id?"selected":""} onClick={()=>onSelect(task.id)}><span className={`exception-symbol ${exception.type}`}><WarningCircle size={21}/></span><span><strong>{task.machineId} · {t(task.machineKey)}</strong><small>{t(exception.type)} · {duration(exception.startedAt,now,lang)}</small></span><b>{t(exception.type)}</b><CaretRight size={17}/></button>;})}</div>;
}

function ExceptionTaskDetail({task,tasks,now,t,lang,onFallbackAssign,onOpenEquipment}){
  const [assigning,setAssigning]=useState(false);
  useEffect(()=>setAssigning(false),[task?.id]);
  if(!task)return <div className="detail-empty"><ListChecks size={38}/><strong>{t("orderDetail")}</strong><span>{t("selectOrder")}</span></div>;
  const exception=getException(task,now);
  const canFallback=task.status==="reported";
  return <article className="exception-detail"><header><span className="machine-block"><Factory size={31}/></span><div><div><h2>{task.machineId} · {t(task.machineKey)}</h2><span className={`exception-badge ${exception?.type||""}`}><WarningCircle size={15}/>{t(exception?.type||"withinSla")}</span></div><p>{task.id} · {task.location}</p></div></header><SlaIndicator task={task} now={now} t={t} lang={lang}/><div className="fact-grid"><div><WarningCircle size={18}/><span>{t("fault")}</span><strong>{t(task.issueKey)}</strong></div><div><User size={18}/><span>{t("reporter")}</span><strong>{task.reporter}</strong></div><div><UsersThree size={18}/><span>{t("technician")}</span><strong>{task.assignee||t("unassigned")}</strong></div><div><Clock size={18}/><span>{t("reported")}</span><strong>{clock(task.reportedAt,lang)}</strong></div></div><div className="exception-content-grid"><div><EvidencePreview task={task} t={t}/><Timeline task={task} t={t} lang={lang}/><div className="exception-alert"><WarningCircle size={20}/><p>{exception?.type==="repeatSuspected"?t("repeatHint"):t("exceptionAlert")}</p></div><div className="exception-actions">{canFallback&&<button className="primary-button" onClick={()=>setAssigning(value=>!value)}><UserPlus size={19}/>{t("adminFallback")}</button>}<button className="secondary-button" onClick={onOpenEquipment}><Factory size={19}/>{t("viewEquipmentRecord")}</button></div>{assigning&&<div className="exception-assign"><strong>{t("chooseTechnician")}</strong><div>{technicians.map(tech=><button key={tech.name} onClick={()=>{onFallbackAssign(task.id,tech);setAssigning(false);}}><img src={tech.avatar} alt=""/><span>{tech.name}</span><CaretRight size={15}/></button>)}</div></div>}</div><RecentMachineHistory task={task} tasks={tasks} now={now} t={t} lang={lang}/></div></article>;
}

function ExceptionCenter({tasks,setTasks,now,t,lang,notify,setSection,focusTaskId}){
  const exceptions=useMemo(()=>tasks.filter(task=>getException(task,now)).sort((a,b)=>{const order={noClaim:0,repairOverdue:1,acceptanceOverdue:2,repeatSuspected:3};return order[getException(a,now).type]-order[getException(b,now).type];}),[tasks,now]);
  const [filter,setFilter]=useState("all"),[selectedId,setSelectedId]=useState(focusTaskId||exceptions[0]?.id);
  const visible=filter==="all"?exceptions:exceptions.filter(task=>matchesExceptionType(task,filter,now));
  const selected=visible.find(task=>task.id===selectedId)||visible[0];
  useEffect(()=>{if(visible.length&&!visible.some(task=>task.id===selectedId))setSelectedId(visible[0].id);},[visible,selectedId]);
  useEffect(()=>{if(focusTaskId&&exceptions.some(task=>task.id===focusTaskId)){setFilter("all");setSelectedId(focusTaskId);}},[focusTaskId,exceptions]);
  const fallback=(id,tech)=>{setTasks(current=>current.map(task=>task.id===id&&task.status==="reported"?{...task,status:"assigned",assignee:tech.name,avatar:tech.avatar,acceptedAt:Date.now(),assignedByAdmin:true}:task));notify(`${t("assignedTo")} ${tech.name}`);};
  const metricItems=[["all","urgentTotal",WarningCircle],["noClaim","noClaim",Clock],["repairOverdue","repairOverdue",Wrench],["acceptanceOverdue","acceptanceOverdue",CheckCircle]];
  return <><PageHeading title={t("exceptionCenterTitle")} sub={t("exceptionCenterSub")} live t={t}/><section className="metric-strip exception-metrics" aria-label={t("exceptionCenterTitle")}>{metricItems.map(([key,label,Icon])=>{const count=key==="all"?exceptions.length:exceptions.filter(task=>matchesExceptionType(task,key,now)).length;return <button key={key} className={`metric exception-metric ${filter===key?"active":""}`} onClick={()=>setFilter(key)} aria-pressed={filter===key}><Icon size={25}/><span><b>{t(label)}</b><small>{key==="all"?t("exceptionCenterSub"):t(key==="noClaim"?"claimRule":key==="repairOverdue"?"repairRule":"acceptanceRule")}</small></span><strong>{count}</strong></button>;})}</section><section className="workspace exception-workspace"><div className="workspace-head"><div><WarningCircle size={22}/><h2>{t(filter==="all"?"urgentTotal":filter)}</h2><span>{visible.length}</span></div></div><div className="exception-grid"><ExceptionList items={visible} selectedId={selected?.id} onSelect={setSelectedId} t={t} lang={lang} now={now}/><ExceptionTaskDetail task={selected} tasks={tasks} now={now} t={t} lang={lang} onFallbackAssign={fallback} onOpenEquipment={()=>setSection("equipment")}/></div></section></>;
}

function OrderActivity({task,now,t,lang}){
  const transferEvents=(task.transfers||[]).map(item=>[item.at,item.from,`${t("eventTransferred")} ${item.to}`,ArrowsLeftRight]);
  const alertEvents=(task.alerts||[]).map(item=>[item.at,item.by,t("eventProblem"),WarningCircle]);
  const events=[
    [task.reportedAt,task.reporter,t("eventReported"),ClipboardText],
    [task.acceptedAt,task.acceptedBy||task.assignee,t("eventAccepted"),UserPlus],
    [task.repairStartedAt,task.assignee,t("eventRepairStarted"),Wrench],
    [task.repairCompletedAt,task.assignee,t("eventRepairCompleted"),CheckCircle],
    [task.closedAt,task.reporter,t("eventClosed"),ShieldCheck],
    ...transferEvents,...alertEvents,
  ].filter(([time])=>time).sort((a,b)=>b[0]-a[0]);
  return <section className="activity-log"><h3><Clock size={19}/>{t("activityLog")}</h3>{events.map(([time,person,label,Icon])=><div key={`${time}-${label}`}><span><Icon size={16}/></span><p><strong>{relativeTime(time,now,lang)}</strong><b>{person} {label}</b><small>{clock(time,lang)}</small></p></div>)}</section>;
}

function OrderDetailDrawer({task,onClose,now,t,lang}){
  useEffect(()=>{if(!task)return;const close=event=>event.key==="Escape"&&onClose();document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close);},[task,onClose]);
  if(!task)return null;
  const photos=evidencePhotos(task);
  return <div className="drawer-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><aside className="order-drawer" role="dialog" aria-modal="true" aria-label={t("fullOrderDetail")}><header><div><span className="drawer-machine"><Factory size={23}/></span><span><small>{t("fullOrderDetail")}</small><strong>{task.id}</strong></span></div><button onClick={onClose} aria-label={t("closeDetail")}><XCircle size={25}/></button></header><div className="drawer-scroll"><TaskDetail task={task} now={now} t={t} lang={lang} showFallback={false}/>{(task.note||photos.length)&&<section className="order-evidence"><h3><Camera size={19}/>{t("orderEvidence")}</h3>{task.note&&<p>{task.note}</p>}<div>{photos.map((src,index)=><figure key={`${src}-${index}`}><img src={src} alt={`${t("siteEvidence")} ${index+1}`}/><figcaption>{index<(task.photos?.length||0)?t("faultPhoto"):t("resultPhoto")}</figcaption></figure>)}</div></section>}<OrderActivity task={task} now={now} t={t} lang={lang}/></div><footer><button onClick={onClose}>{t("closeDetail")}</button></footer></aside></div>;
}

function EquipmentView({tasks,t}){return <main className="simple-page"><PageHeading title={t("equipmentTitle")} sub={t("adminSub")}/><div className="equipment-grid">{machines.map(machine=>{const active=tasks.filter(x=>x.machineId===machine.id&&x.status!=="closed").length;return <article key={machine.id}><Factory size={27}/><div><strong>{machine.id} · {t(machine.nameKey)}</strong><span>{machine.line} · {machine.station}</span></div><b className={active?"warning-text":"ok-text"}>{active?`${active} ${t("ordersCount")}`:"OK"}</b></article>;})}</div></main>;}
function TeamView({tasks,t}){return <main className="simple-page"><PageHeading title={t("teamTitle")} sub={t("normalClaimHint")}/><div className="team-grid">{technicians.map(tech=>{const active=tasks.filter(x=>x.assignee===tech.name&&!['closed','acceptance'].includes(x.status)).length;return <article key={tech.name}><img src={tech.avatar} alt=""/><div><strong>{tech.name}</strong><span>{active?t("busy"):t("teamAvailable")}</span></div><b>{active} {t("ordersCount")}</b></article>;})}</div></main>;}
function Settings({t,lang,setLang,onReset}){return <main className="simple-page settings-page"><PageHeading title={t("settingsTitle")} sub={t("settingsHint")}/><section><h2>{t("languageSetting")}</h2><div className="language-cards">{[["bm","Bahasa Melayu"],["zh","中文"],["en","English"]].map(([key,label])=><button key={key} className={lang===key?"active":""} onClick={()=>setLang(key)}><span>{label}</span>{lang===key&&<CheckCircle size={20} weight="fill"/>}</button>)}</div>{onReset&&<button className="secondary-button" onClick={onReset}>{t("demoReset")}</button>}</section></main>;}
function PageHeading({title,sub,live,t}){return <div className="page-heading"><div><h1>{title}</h1><p>{sub}</p></div>{live&&<span className="live-chip"><i/>{t("live")}</span>}</div>;}

const portalConfigs={
  admin:{title:"adminPortal",items:[["live","navLive",ClipboardText],["exceptions","navExceptions",WarningCircle],["equipment","navEquipment",Cube],["history","navHistory",ListChecks],["reports","navReports",ChartBar],["people","navPeopleAnalysis",UsersThree],["faults","navFaultAnalysis",WarningCircle],["settings","navSettings",Gear]]},
  operator:{title:"operatorPortal",items:[["report","navReport",PaperPlaneTilt],["current","navCurrent",ClipboardText],["history","navHistory",ListChecks],["equipment","navEquipment",Cube],["settings","navSettings",Gear]]},
  technician:{title:"technicianPortal",items:[["available","navAvailable",UsersThree],["current","navCurrent",Wrench],["history","navHistory",ListChecks],["equipment","navEquipment",Cube],["settings","navSettings",Gear]]},
};
function PortalSidebar({role,section,setSection,setRole,t,alertCount=0}){
  const config=portalConfigs[role];
  return <aside className="role-sidebar"><div className="portal-name"><span className="portal-mark">M4</span><strong>{t(config.title)}</strong></div><small className="nav-caption">{t("workGroup")}</small><nav>{config.items.map(([key,label,Icon])=>{const hasAlert=role==="admin"&&key==="exceptions"&&alertCount>0;return <button key={key} className={`${section===key?"active":""} ${hasAlert?"nav-needs-attention":""}`} onClick={()=>setSection(key)} aria-label={hasAlert?`${t(label)} · ${alertCount} ${t("urgentTotal")}`:t(label)}><Icon size={21}/><span>{t(label)}</span>{hasAlert&&<b className="nav-alert-badge"><WarningCircle size={16} weight="fill"/><em>{alertCount}</em></b>}</button>;})}</nav><div className="sidebar-role-switch"><small>{t("roleGroup")}</small>{[["admin","roleAdmin"],["operator","roleOperator"],["technician","roleTechnician"]].map(([key,label])=><button key={key} className={role===key?"active":""} onClick={()=>setRole(key)}><User size={17}/><span>{t(label)}</span></button>)}<p>{t("factory")} · 07:00–19:00</p></div></aside>;
}

function MobileMenu({open,role,section,setSection,setRole,onClose,t,alertCount=0}){
  useEffect(()=>{if(!open)return;const close=event=>event.key==="Escape"&&onClose();document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close);},[open,onClose]);
  if(!open)return null;
  const config=portalConfigs[role];
  return <div className="mobile-menu-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="mobile-menu-sheet" role="dialog" aria-modal="true" aria-label={t("menu")}><header><span><List size={23}/></span><div><strong>{t(config.title)}</strong><small>{t("factory")} · 07:00–19:00</small></div><button onClick={onClose} aria-label={t("closeMenu")}><XCircle size={25}/></button></header><nav>{config.items.map(([key,label,Icon])=>{const hasAlert=role==="admin"&&key==="exceptions"&&alertCount>0;return <button key={key} className={`${section===key?"active":""} ${hasAlert?"nav-needs-attention":""}`} onClick={()=>{setSection(key);onClose();}} aria-label={hasAlert?`${t(label)} · ${alertCount} ${t("urgentTotal")}`:t(label)}><Icon size={22}/><span>{t(label)}</span>{hasAlert?<b className="nav-alert-badge"><WarningCircle size={16} weight="fill"/><em>{alertCount}</em></b>:section===key&&<Check size={17} weight="bold"/>}</button>;})}</nav><footer><small>{t("roleGroup")}</small><div>{[["admin","roleAdmin"],["operator","roleOperator"],["technician","roleTechnician"]].map(([key,label])=><button key={key} className={role===key?"active":""} onClick={()=>{setRole(key);onClose();}}><User size={18}/><span>{t(label)}</span></button>)}</div></footer></section></div>;
}

function PersistentActionBar({actions,t,className=""}){
  const visible=actions.filter(Boolean);
  if(!visible.length)return null;
  return <aside className={`persistent-action-bar ${className}`} aria-label={t("quickActions")}><div><span className="action-context"><b>{t("quickActions")}</b><small>{visible.find(action=>action.primary)?.label||visible[0].label}</small></span><div className="action-buttons">{visible.map(({key,label,Icon,onClick,primary=false,danger=false,disabled=false})=><button key={key} className={`${primary?"primary":""} ${danger?"danger":""}`} onClick={onClick} disabled={disabled}><Icon size={21}/><span>{label}</span></button>)}</div></div></aside>;
}

function WorkerOrdersPage({items,title,t,lang,now,emptyHint,focusTaskId,onAccept,onReject,actionFactory}){
  const [selectedId,setSelectedId]=useState(focusTaskId||items[0]?.id),[drawerId,setDrawerId]=useState("");
  const selected=items.find(task=>task.id===selectedId)||items[0];
  useEffect(()=>{if(items.length&&!items.some(task=>task.id===selectedId))setSelectedId(items[0].id);},[items,selectedId]);
  useEffect(()=>{if(focusTaskId&&items.some(task=>task.id===focusTaskId))setSelectedId(focusTaskId);},[focusTaskId,items]);
  const openDetail=id=>{setSelectedId(id);setDrawerId(id);};
  const actions=actionFactory?actionFactory(selected):[];
  return <><main className="simple-page worker-orders-page"><PageHeading title={title} sub={t("adminSub")}/><section className="workspace"><div className="workspace-head"><div><ClipboardText size={22}/><h2>{title}</h2><span>{items.length}</span></div></div><div className="workspace-grid"><TaskList tasks={items} selectedId={selected?.id} onSelect={openDetail} t={t} lang={lang} now={now} emptyHint={emptyHint}/><TaskDetail task={selected} now={now} t={t} lang={lang} showFallback={false} onAccept={onAccept} onReject={onReject}/></div></section><OrderDetailDrawer task={items.find(task=>task.id===drawerId)} onClose={()=>setDrawerId("")} now={now} t={t} lang={lang}/></main><PersistentActionBar actions={actions} t={t}/></>;
}

function HistoryOrdersPage({tasks,t,lang,now,focusTaskId}){
  const [query,setQuery]=useState(""),[tech,setTech]=useState("all"),[range,setRange]=useState("all"),[selectedId,setSelectedId]=useState(focusTaskId||""),[drawerId,setDrawerId]=useState("");
  const history=tasks.filter(task=>task.status==="closed").filter(task=>range==="all"||task.reportedAt>=now-(range==="week"?7:30)*86_400_000).filter(task=>tech==="all"||task.assignee===tech).filter(task=>`${task.id} ${task.machineId} ${t(task.machineKey)} ${t(task.issueKey)} ${task.assignee||""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.closedAt-a.closedAt);
  const selected=history.find(task=>task.id===selectedId)||history[0];
  useEffect(()=>{if(focusTaskId&&history.some(task=>task.id===focusTaskId))setSelectedId(focusTaskId);},[focusTaskId,history]);
  const openDetail=id=>{setSelectedId(id);setDrawerId(id);};
  return <main className="simple-page history-page"><PageHeading title={t("historyTitle")} sub={t("reportsSub")}/><div className="history-filters"><label><MagnifyingGlass size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t("historySearch")}/></label><select value={tech} onChange={event=>setTech(event.target.value)}><option value="all">{t("allTechnicians")}</option>{technicians.map(item=><option key={item.name}>{item.name}</option>)}</select><select value={range} onChange={event=>setRange(event.target.value)}><option value="all">{t("allPeriods")}</option><option value="week">{t("last7Days")}</option><option value="month">{t("last30Days")}</option></select></div><section className="workspace history-workspace"><div className="workspace-head"><div><ListChecks size={22}/><h2>{t("historyTitle")}</h2><span>{history.length}</span></div></div><div className="workspace-grid"><TaskList tasks={history} selectedId={selected?.id} onSelect={openDetail} t={t} lang={lang} now={now} emptyHint={t("emptyHistory")}/><TaskDetail task={selected} now={now} t={t} lang={lang} showFallback={false}/></div></section><OrderDetailDrawer task={tasks.find(task=>task.id===drawerId)} onClose={()=>setDrawerId("")} now={now} t={t} lang={lang}/></main>;
}

function PeopleAnalysis({tasks,t,lang,compact=false}){
  const rows=technicianStats(tasks);
  return <section className={`analysis-card people-analysis ${compact?"compact":""}`}><header><div><UsersThree size={23}/><span><h2>{t("personnelAnalysisTitle")}</h2><p>{t("personnelAnalysisSub")}</p></span></div></header><div className="analysis-table"><div className="analysis-table-head"><span>{t("technician")}</span><span>{t("acceptedOrders")}</span><span>{t("avgClaim")}</span><span>{t("avgFix")}</span><span>{t("completion")}</span><span>{t("taskLoad")}</span></div>{rows.map(row=><div className="analysis-table-row" key={row.name}><span className="person-cell"><img src={row.avatar} alt=""/><b>{row.name}</b></span><strong>{row.accepted}</strong><span>{formatMinutes(row.avgResponse,lang)}</span><span>{formatMinutes(row.avgRepair,lang)}</span><span><b>{row.completion}%</b><i className="micro-bar"><em style={{width:`${row.completion}%`}}/></i></span><strong className={row.active?"warning-text":"ok-text"}>{row.active}</strong></div>)}</div></section>;
}

function FaultAnalysis({tasks,t,compact=false}){
  const machinesData=groupedStats(tasks,task=>task.machineId);
  const issueData=groupedStats(tasks,task=>task.issueKey);
  const causeData=groupedStats(tasks,task=>task.result?.causeKey);
  const machineName=id=>{const machine=machines.find(item=>item.id===id);return machine?`${id} · ${t(machine.nameKey)}`:id;};
  return <section className={`analysis-card fault-analysis ${compact?"compact":""}`}><header><div><WarningCircle size={23}/><span><h2>{t("faultAnalysisTitle")}</h2><p>{t("faultAnalysisSub")}</p></span></div></header><div className="fault-columns"><div><h3>{t("machineFaultRate")}</h3>{machinesData.map(item=><div className="breakdown-row" key={item.key}><span><b>{machineName(item.key)}</b><small>{item.count} · {item.share}%</small></span><i><em style={{width:`${item.share}%`}}/></i></div>)}</div><div><h3>{t("faultCauses")}</h3>{causeData.map(item=><div className="cause-row" key={item.key}><span>{t(item.key)}</span><b>{item.count}</b><small>{item.share}%</small></div>)}{!causeData.length&&<div className="search-empty">—</div>}</div>{!compact&&<div><h3>{t("faultTypeBreakdown")}</h3>{issueData.map(item=><div className="cause-row" key={item.key}><span>{t(item.key)}</span><b>{item.count}</b><small>{item.share}%</small></div>)}</div>}</div></section>;
}

function ReportPage({tasks,t,lang,now}){
  const [period,setPeriod]=useState("weekly");
  const data=periodTasks(tasks,period,now);
  const completed=data.filter(task=>task.repairCompletedAt);
  const techRows=technicianStats(data);
  const machinesData=groupedStats(data,task=>task.machineId);
  const causesData=groupedStats(data,task=>task.result?.causeKey);
  const metrics=[
    ["totalOrders",data.length,ClipboardText],["closedOrders",data.filter(task=>task.status==="closed").length,CheckCircle],
    ["closureRate",`${percentage(data.filter(task=>task.status==="closed").length,data.length)}%`,ChartBar],
    ["avgResponse",formatMinutes(average(data.map(task=>minutesBetween(task.reportedAt,task.acceptedAt))),lang),Clock],
    ["avgRepair",formatMinutes(average(completed.map(task=>minutesBetween(task.repairStartedAt,task.repairCompletedAt))),lang),Wrench],
  ];
  const exportCsv=()=>{const rows=[[t("reportedDate"),t("orderId"),t("machine"),t("fault"),t("technician"),t("orderStatus"),t("avgResponse"),t("avgRepair")],...data.map(task=>[new Date(task.reportedAt).toISOString(),task.id,`${task.machineId} ${t(task.machineKey)}`,t(task.issueKey),task.assignee||"",t(statusKey(task.status)),Math.round(minutesBetween(task.reportedAt,task.acceptedAt)||0),Math.round(minutesBetween(task.repairStartedAt,task.repairCompletedAt)||0)])];const csv="\uFEFF"+rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`M4-${period}-${new Date(now).toISOString().slice(0,10)}.csv`;link.style.display="none";document.body.appendChild(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <main className="simple-page report-page"><div className="page-heading report-heading"><div><h1>{t("reportsTitle")}</h1><p>{t("reportsSub")}</p></div><div className="report-actions"><div className="segmented"><button className={period==="weekly"?"active":""} onClick={()=>setPeriod("weekly")}>{t("weekly")}</button><button className={period==="monthly"?"active":""} onClick={()=>setPeriod("monthly")}>{t("monthly")}</button></div><button className="export-report" onClick={exportCsv}><DownloadSimple size={19}/>{t("exportCsv")}</button></div></div><section className="report-metrics">{metrics.map(([key,value,Icon])=><article key={key}><Icon size={23}/><span>{t(key)}</span><strong>{value}</strong></article>)}</section><PeopleAnalysis tasks={data} t={t} lang={lang}/><section className="report-split"><div className="analysis-card"><header><div><Factory size={23}/><span><h2>{t("machineFaultRate")}</h2><p>{t("machineBreakdown")}</p></span></div></header>{machinesData.map(item=><div className="report-breakdown" key={item.key}><span>{item.key}</span><i><em style={{width:`${item.share}%`}}/></i><strong>{item.count}</strong><small>{item.share}%</small></div>)}</div><div className="analysis-card"><header><div><WarningCircle size={23}/><span><h2>{t("faultCauses")}</h2><p>{t("faultTypeBreakdown")}</p></span></div></header>{causesData.map(item=><div className="report-breakdown" key={item.key}><span>{t(item.key)}</span><i><em style={{width:`${item.share}%`}}/></i><strong>{item.count}</strong><small>{item.share}%</small></div>)}</div></section></main>;
}

function DashboardInsights({tasks,t,lang}){return <div className="dashboard-insights"><PeopleAnalysis tasks={tasks} t={t} lang={lang} compact/><FaultAnalysis tasks={tasks} t={t} compact/></div>;}

function AdminApp({tasks,setTasks,now,t,lang,notify,setLang,section,setSection,setRole,focusTaskId}){
  const statusFilters={activeOrders:task=>task.status!=="closed",waitingClaim:task=>task.status==="reported",repairing:task=>["assigned","repairing"].includes(task.status),waitingAccept:task=>task.status==="acceptance"};
  const [statusFilter,setStatusFilter]=useState("activeOrders");
  const activeTasks=useMemo(()=>tasks.filter(statusFilters[statusFilter]),[tasks,statusFilter]);
  const [selectedId,setSelectedId]=useState(activeTasks[0]?.id),[drawerId,setDrawerId]=useState("");const selected=activeTasks.find(x=>x.id===selectedId)||activeTasks[0];
  useEffect(()=>{if(activeTasks.length&&!activeTasks.some(x=>x.id===selectedId))setSelectedId(activeTasks[0].id);},[activeTasks,selectedId]);
  useEffect(()=>{const focused=tasks.find(task=>task.id===focusTaskId&&task.status!=="closed");if(!focused)return;const nextFilter=focused.status==="reported"?"waitingClaim":["assigned","repairing"].includes(focused.status)?"repairing":"waitingAccept";setStatusFilter(nextFilter);setSelectedId(focused.id);},[focusTaskId,tasks]);
  const fallback=(id,tech)=>{setTasks(current=>current.map(task=>task.id===id&&task.status==="reported"?{...task,status:"assigned",assignee:tech.name,avatar:tech.avatar,acceptedAt:Date.now(),assignedByAdmin:true}:task));notify(`${t("assignedTo")} ${tech.name}`);};
  const openDetail=id=>{setSelectedId(id);setDrawerId(id);};
  const applyStatusFilter=key=>{setStatusFilter(key);if(window.matchMedia("(max-width:760px)").matches)window.requestAnimationFrame(()=>document.getElementById("admin-task-workspace")?.scrollIntoView({block:"start"}));};
  const metrics=[["activeOrders",ClipboardText],["waitingClaim",Clock],["repairing",Wrench],["waitingAccept",CheckCircle]].map(([key,Icon])=>[key,tasks.filter(statusFilters[key]).length,Icon]);
  const alertCount=tasks.filter(task=>getException(task,now)).length;
  const viewExceptions=()=>{setSection("exceptions");window.requestAnimationFrame(()=>window.scrollTo({top:0,behavior:"smooth"}));};
  const adminActions=alertCount?[{key:"view-exceptions",label:`${t("viewExceptionStatus")} · ${alertCount}`,Icon:WarningCircle,onClick:viewExceptions,primary:true}]:[];
  return <><div className="role-layout"><PortalSidebar role="admin" section={section} setSection={setSection} setRole={setRole} t={t} alertCount={alertCount}/><main className="role-main admin-main">
    {section==="exceptions"?<ExceptionCenter tasks={tasks} setTasks={setTasks} now={now} t={t} lang={lang} notify={notify} setSection={setSection} focusTaskId={focusTaskId}/>:section==="settings"?<Settings t={t} lang={lang} setLang={setLang} onReset={()=>{const next=seedTasks();setTasks(next);notify(t("resetDone"));}}/>:section==="equipment"?<EquipmentView tasks={tasks} t={t}/>:section==="history"?<HistoryOrdersPage tasks={tasks} t={t} lang={lang} now={now} focusTaskId={focusTaskId}/>:section==="reports"?<ReportPage tasks={tasks} t={t} lang={lang} now={now}/>:section==="people"?<main className="simple-page analysis-page"><PageHeading title={t("personnelAnalysisTitle")} sub={t("personnelAnalysisSub")}/><PeopleAnalysis tasks={tasks} t={t} lang={lang}/></main>:section==="faults"?<main className="simple-page analysis-page"><PageHeading title={t("faultAnalysisTitle")} sub={t("faultAnalysisSub")}/><FaultAnalysis tasks={tasks} t={t}/></main>:<><PageHeading title={t("adminTitle")} sub={t("adminSub")} live t={t}/><section className="metric-strip" aria-label={t("statusOverview")}>{metrics.map(([key,value,Icon])=><button className={`metric metric-filter ${statusFilter===key?"active":""}`} data-filter={key} key={key} onClick={()=>applyStatusFilter(key)} aria-pressed={statusFilter===key}><Icon size={27}/><span className="metric-label"><b>{t(key)}</b><small>{t("viewOrders")}</small></span><strong>{value}</strong><CaretRight size={17}/></button>)}</section><section className="workspace" id="admin-task-workspace"><div className="workspace-head"><div><Wrench size={22}/><h2>{t(statusFilter)}</h2><span>{activeTasks.length}</span></div></div><div className="workspace-grid"><TaskList tasks={activeTasks} selectedId={selected?.id} onSelect={openDetail} t={t} lang={lang} now={now}/><TaskDetail task={selected} now={now} t={t} lang={lang} onFallbackAssign={fallback}/></div></section><DashboardInsights tasks={tasks} t={t} lang={lang}/><OrderDetailDrawer task={tasks.find(task=>task.id===drawerId)} onClose={()=>setDrawerId("")} now={now} t={t} lang={lang}/></>}
  </main></div><PersistentActionBar actions={adminActions} t={t} className="admin-mobile-action-bar"/></>;
}

function PhotoInput({label,hint,value,onChange,t}){const read=file=>{if(!file||!file.type.startsWith("image/"))return;const reader=new FileReader();reader.onload=()=>onChange(reader.result);reader.readAsDataURL(file);};return <label className={`photo-input ${value?"has-photo":""}`}><input type="file" accept="image/*" capture="environment" onChange={e=>read(e.target.files?.[0])}/>{value?<img src={value} alt={t("photoUploaded")}/>:<Camera size={28}/>}<span><strong>{label}</strong><small>{value?t("photoUploaded"):hint}</small></span></label>;}
function TechnicianPhotoInput({label,hint,value,onChange,t}){const read=file=>{if(!file||!file.type.startsWith("image/"))return;const reader=new FileReader();reader.onload=()=>onChange(reader.result);reader.readAsDataURL(file);};const choose=event=>{read(event.target.files?.[0]);event.target.value="";};return <div className={`technician-photo-input ${value?"has-photo":""}`}><div className="technician-photo-preview">{value?<img src={value} alt={t("photoUploaded")}/>:<Camera size={29}/>}<span><strong>{label}</strong><small>{value?t("photoUploaded"):hint}</small></span></div><div className="photo-source-actions"><label><input type="file" accept="image/*" capture="environment" onChange={choose}/><Camera size={18}/>{t(value?"retakePhoto":"takePhoto")}</label><label><input type="file" accept="image/*" onChange={choose}/><UploadSimple size={18}/>{t(value?"replaceFromDevice":"localPhoto")}</label></div></div>;}

function TransferDialog({task,tasks,onTransfer,onClose,t}){
  useEffect(()=>{if(!task)return;const close=event=>event.key==="Escape"&&onClose();document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close);},[task,onClose]);
  if(!task)return null;
  const options=technicians.filter(tech=>tech.name!==task.assignee);
  return <div className="transfer-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="transfer-dialog" role="dialog" aria-modal="true" aria-label={t("transferTitle")}><header><span><ArrowsLeftRight size={23}/></span><div><h2>{t("transferTitle")}</h2><p>{task.id} · {task.machineId}</p></div><button onClick={onClose} aria-label={t("cancel")}><XCircle size={24}/></button></header><div className="transfer-copy"><strong>{t("transferHint")}</strong><p>{t("transferAuditHint")}</p></div><div className="transfer-options">{options.map(tech=>{const workload=tasks.filter(item=>item.assignee===tech.name&&["assigned","repairing"].includes(item.status)).length;return <button key={tech.name} onClick={()=>onTransfer(tech)}><img src={tech.avatar} alt=""/><span><strong>{tech.name}</strong><small>{workload?`${t("taskLoad")} · ${workload}`:t("teamAvailable")}</small></span><b>{t("transferTo")}</b><CaretRight size={16}/></button>;})}</div><footer><button onClick={onClose}>{t("cancel")}</button></footer></section></div>;
}
function OperatorApp({tasks,setTasks,now,t,lang,notify,section,setSection,setLang,focusTaskId}){
  const [machine,setMachine]=useState(null),[fault,setFault]=useState(""),[photo,setPhoto]=useState(""),[note,setNote]=useState(""),[qrBusy,setQrBusy]=useState(false),[qrFallback,setQrFallback]=useState(false),[detailTaskId,setDetailTaskId]=useState("");
  const mine=tasks.filter(x=>x.reporter==="Lim Wei").sort((a,b)=>b.reportedAt-a.reportedAt);
  const uploadQr=async file=>{if(!file)return;if(!file.type.startsWith("image/"))return notify(t("qrFileError"));setQrBusy(true);setQrFallback(false);try{if(!("BarcodeDetector" in window))throw new Error("unsupported");const detector=new window.BarcodeDetector({formats:["qr_code"]});const bitmap=await createImageBitmap(file);const codes=await detector.detect(bitmap);bitmap.close?.();const raw=codes[0]?.rawValue?.toUpperCase()||"";const found=machines.find(item=>raw.includes(item.id.toUpperCase()));if(!found)throw new Error("unknown");setMachine(found);notify(`${t("qrRecognized")} ${found.id}`);}catch{setQrFallback(true);notify(t("qrNotRecognized"));}finally{setQrBusy(false);}};
  const submit=()=>{if(!machine||!fault)return notify(t("requiredFault"));if(!photo)return notify(t("requiredPhoto"));const created={id:`WO-${Date.now().toString().slice(-8)}`,machineId:machine.id,machineKey:machine.nameKey,issueKey:fault,status:"reported",reporter:"Lim Wei",location:`${machine.line} · ${machine.station}`,reportedAt:Date.now(),photo,photos:[photo],note};setTasks(current=>[created,...current]);setMachine(null);setFault("");setPhoto("");setNote("");notify(t("reportSuccess"));};
  const close=id=>{setTasks(current=>current.map(task=>task.id===id&&task.status==="acceptance"?{...task,status:"closed",closedAt:Date.now()}:task));notify(t("closedSuccess"));};
  const rework=id=>{setTasks(current=>current.map(task=>task.id===id&&task.status==="acceptance"?{...task,status:"repairing",repairStartedAt:Date.now(),repairCompletedAt:null,closedAt:null}:task));notify(t("reworkSuccess"));};
  const reportProblem=task=>{if(!task)return notify(t("selectOrderFirst"));setTasks(current=>current.map(item=>item.id===task.id?{...item,alerts:[...(item.alerts||[]),{by:"Lim Wei",at:Date.now()}]}:item));notify(t("problemReported"));};
  const newReportActions=task=>[{key:"problem",label:t("reportProblem"),Icon:WarningCircle,onClick:()=>reportProblem(task),danger:true},{key:"new-report",label:t("navReport"),Icon:PaperPlaneTilt,onClick:()=>setSection("report"),primary:true}];
  if(section==="current")return <WorkerOrdersPage items={mine.filter(task=>task.status!=="closed")} title={t("currentTitle")} t={t} lang={lang} now={now} focusTaskId={focusTaskId} onAccept={close} onReject={rework} actionFactory={task=>task?.status==="acceptance"?[{key:"rework",label:t("rejectResult"),Icon:XCircle,onClick:()=>rework(task.id),danger:true},{key:"accept",label:t("acceptResult"),Icon:CheckCircle,onClick:()=>close(task.id),primary:true}]:newReportActions(task)}/>;
  if(section==="history")return <WorkerOrdersPage items={mine.filter(task=>task.status==="closed")} title={t("historyTitle")} t={t} lang={lang} now={now} emptyHint={t("emptyHistory")} focusTaskId={focusTaskId} actionFactory={newReportActions}/>;
  if(section==="equipment")return <><EquipmentView tasks={tasks} t={t}/><PersistentActionBar actions={newReportActions()} t={t}/></>;
  if(section==="settings")return <><Settings t={t} lang={lang} setLang={setLang}/><PersistentActionBar actions={newReportActions()} t={t}/></>;
  const clearDraft=()=>{setMachine(null);setFault("");setPhoto("");setNote("");setQrFallback(false);notify(t("draftCleared"));};
  const reportActions=[{key:"cancel",label:t("cancelDraft"),Icon:XCircle,onClick:clearDraft,danger:true,disabled:!machine&&!fault&&!photo&&!note},{key:"submit",label:t("submitRepair"),Icon:PaperPlaneTilt,onClick:submit,primary:true,disabled:!machine||!fault||!photo}];
  return <><main className="worker-page"><div className="worker-heading"><span className="role-icon"><Scan size={28}/></span><div><h1>{t("operatorTitle")}</h1><p>{t("operatorSub")}</p></div></div><div className="worker-grid"><section className="report-panel">
    {!machine?<div className="scan-state"><span><QrCode size={74}/></span><h2>{t("scanMachine")}</h2><p>{t("scanHint")}</p><div className="scan-actions"><button className="primary-button" onClick={()=>setMachine(machines[0])}><Scan size={21}/>{t("startScan")}</button><label className={`qr-upload-button ${qrBusy?"busy":""}`}><input type="file" accept="image/*" disabled={qrBusy} onChange={event=>{uploadQr(event.target.files?.[0]);event.target.value="";}}/><UploadSimple size={21}/>{qrBusy?t("readingQr"):t("uploadQr")}</label></div><small className="upload-qr-hint">{t("uploadQrHint")}</small>{qrFallback&&<div className="qr-fallback"><strong>{t("confirmMachine")}</strong><p>{t("qrFallbackHint")}</p><div>{machines.map(item=><button key={item.id} onClick={()=>{setMachine(item);setQrFallback(false);}}><Factory size={18}/><span>{item.id}<small>{t(item.nameKey)}</small></span></button>)}</div></div>}</div>:<><div className="scanned-machine"><span><Factory size={31}/></span><div><small>{t("scanned")}</small><strong>{machine.id} · {t(machine.nameKey)}</strong><p>{machine.line} · {machine.station}</p></div><button onClick={()=>{setMachine(null);setQrFallback(false);}}>{t("scanAgain")}</button></div><fieldset className="fault-picker"><legend>{t("chooseFault")}</legend><div>{faults.map(key=><button type="button" key={key} className={fault===key?"selected":""} onClick={()=>setFault(key)}><WarningCircle size={21}/><span>{t(key)}</span>{fault===key&&<Check size={17} weight="bold"/>}</button>)}</div></fieldset><PhotoInput label={t("addPhoto")} hint={t("photoHint")} value={photo} onChange={setPhoto} t={t}/><label className="text-field"><span>{t("noteOptional")}</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={t("notePlaceholder")} maxLength={240}/></label></>}
  </section><section className="my-orders"><header><h2>{t("myOrders")}</h2><span>{mine.length}</span></header>{mine.map(task=><article className="clickable-order" key={task.id}><div className="order-summary" role="button" tabIndex="0" onClick={()=>setDetailTaskId(task.id)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setDetailTaskId(task.id);}}}><span className={`status-symbol ${task.status}`}><StatusIcon status={task.status} size={20}/></span><div><strong>{task.machineId} · {t(task.machineKey)}</strong><small>{task.id} · {duration(task.reportedAt,task.closedAt||now,lang)}</small></div><StatusBadge task={task} t={t}/><CaretRight className="order-caret" size={17}/></div>{task.status==="acceptance"&&<div className="acceptance-box"><p>{t("acceptanceHint")}</p>{task.result&&<blockquote>{task.result.note}</blockquote>}<div><button className="reject-button" onClick={()=>rework(task.id)}><XCircle size={19}/>{t("rejectResult")}</button><button className="accept-button" onClick={()=>close(task.id)}><CheckCircle size={19}/>{t("acceptResult")}</button></div></div>}</article>)}</section></div><OrderDetailDrawer task={tasks.find(task=>task.id===detailTaskId)} onClose={()=>setDetailTaskId("")} now={now} t={t} lang={lang}/></main><PersistentActionBar actions={reportActions} t={t}/></>;
}

function TechnicianApp({tasks,setTasks,now,updatedAt,t,lang,notify,section,setSection,setLang,focusTaskId}){
  const me=technicians[0];const [selectedId,setSelectedId]=useState(""),[cause,setCause]=useState(""),[note,setNote]=useState(""),[photo,setPhoto]=useState(""),[transferTaskId,setTransferTaskId]=useState("");
  const available=tasks.filter(x=>x.status==="reported"),mine=tasks.filter(x=>x.assignee===me.name&&x.status!=="closed"),history=tasks.filter(x=>x.assignee===me.name&&x.status==="closed"),list=section==="available"?available:mine,selected=list.find(x=>x.id===selectedId)||list[0];
  useEffect(()=>{if(focusTaskId&&list.some(task=>task.id===focusTaskId))setSelectedId(focusTaskId);},[focusTaskId,list]);
  const claim=id=>{const current=tasks.find(task=>task.id===id);if(!current||current.status!=="reported")return notify(t("alreadyClaimed"));setTasks(items=>items.map(task=>task.id===id?{...task,status:"assigned",assignee:me.name,acceptedBy:me.name,avatar:me.avatar,acceptedAt:Date.now()}:task));setSection("current");notify(t("claimedSuccess"));};
  const start=id=>{setTasks(current=>current.map(task=>task.id===id&&task.status==="assigned"?{...task,status:"repairing",repairStartedAt:Date.now()}:task));notify(t("startedSuccess"));};
  const finish=id=>{if(!cause||!note.trim())return notify(t("resultRequired"));setTasks(current=>current.map(task=>task.id===id&&task.status==="repairing"?{...task,status:"acceptance",repairCompletedAt:Date.now(),result:{causeKey:cause,note:note.trim(),photo,photos:photo?[photo]:[]}}:task));setCause("");setNote("");setPhoto("");notify(t("handoverSuccess"));};
  const transfer=tech=>{const task=tasks.find(item=>item.id===transferTaskId);if(!task||task.assignee!==me.name||!["assigned","repairing"].includes(task.status)){setTransferTaskId("");return notify(t("transferUnavailable"));}const at=Date.now();setTasks(current=>current.map(item=>item.id===task.id?{...item,acceptedBy:item.acceptedBy||me.name,assignee:tech.name,avatar:tech.avatar,transfers:[...(item.transfers||[]),{from:me.name,to:tech.name,at}]}:item));setTransferTaskId("");setSelectedId("");notify(`${t("transferSuccess")} ${tech.name}`);};
  const reportProblem=task=>{if(!task)return notify(t("selectOrderFirst"));setTasks(current=>current.map(item=>item.id===task.id?{...item,alerts:[...(item.alerts||[]),{by:me.name,at:Date.now()}]}:item));notify(t("problemReported"));};
  const navigationActions=[{key:"available",label:t("navAvailable"),Icon:UsersThree,onClick:()=>setSection("available")},{key:"current",label:t("navCurrent"),Icon:Wrench,onClick:()=>setSection("current"),primary:true}];
  if(section==="history")return <WorkerOrdersPage items={history} title={t("historyTitle")} t={t} lang={lang} now={now} emptyHint={t("emptyHistory")} focusTaskId={focusTaskId} actionFactory={()=>navigationActions}/>;
  if(section==="equipment")return <><EquipmentView tasks={tasks} t={t}/><PersistentActionBar actions={navigationActions} t={t}/></>;
  if(section==="settings")return <><Settings t={t} lang={lang} setLang={setLang}/><PersistentActionBar actions={navigationActions} t={t}/></>;
  const taskActions=selected?[{key:"problem",label:t("reportProblem"),Icon:WarningCircle,onClick:()=>reportProblem(selected),danger:true},selected.assignee===me.name&&["assigned","repairing"].includes(selected.status)?{key:"transfer",label:t("transferOrder"),Icon:ArrowsLeftRight,onClick:()=>setTransferTaskId(selected.id)}:null,selected.status==="reported"?{key:"claim",label:t("claim"),Icon:UserPlus,onClick:()=>claim(selected.id),primary:true}:selected.status==="assigned"?{key:"start",label:t("startRepair"),Icon:Play,onClick:()=>start(selected.id),primary:true}:selected.status==="repairing"?{key:"finish",label:t("finishAction"),Icon:CheckCircle,onClick:()=>finish(selected.id),primary:true,disabled:!cause||!note.trim()}:null]:[{key:"refresh",label:t("refreshData"),Icon:ArrowsClockwise,onClick:()=>notify(t("refreshDone")),primary:true}];
  return <><main className="worker-page"><div className="worker-heading technician-heading"><img src={me.avatar} alt=""/><div><h1>{t("technicianTitle")}</h1><p>{t("technicianSub")}</p></div><div className="technician-meta"><span className="update-chip"><ArrowsClockwise size={16}/><span>{t("updatedAt")}</span><strong>{clockWithSeconds(updatedAt,lang)}</strong></span><span className="available-chip"><i/>{me.name}</span></div></div><div className="technician-shell"><aside className="tech-list"><div className="list-section-title"><strong>{t(section==="available"?"navAvailable":"navCurrent")}</strong><span>{list.length}</span></div><TaskList tasks={list} selectedId={selected?.id} onSelect={setSelectedId} t={t} lang={lang} now={now} emptyHint={t(section==="available"?"noAvailable":"noMine")}/></aside><section className="tech-detail">{selected?<><div className="tech-machine"><span><Factory size={34}/></span><div><h2>{selected.machineId} · {t(selected.machineKey)}</h2><p><MapPin size={16}/>{selected.location}</p></div><div className="tech-task-actions"><StatusBadge task={selected} t={t}/></div></div><SlaIndicator task={selected} now={now} t={t} lang={lang}/><div className="fault-callout"><WarningCircle size={22}/><div><small>{t("fault")}</small><strong>{t(selected.issueKey)}</strong>{selected.note&&<p>{selected.note}</p>}</div></div><DurationStrip task={selected} now={now} t={t} lang={lang}/><EvidencePreview task={selected} t={t}/><RecentMachineHistory task={selected} tasks={tasks} now={now} t={t} lang={lang}/>
    {selected.status==="reported"&&<div className="claim-zone"><p><UsersThree size={19}/>{t("broadcast")}</p></div>}{selected.status==="assigned"&&<div className="claim-zone"><p><MapPin size={19}/>{t("goToMachine")}</p></div>}{selected.status==="repairing"&&<div className="repair-form"><h3><Wrench size={21}/>{t("submitResult")}</h3><label><span>{t("resultCategory")}</span><select value={cause} onChange={e=>setCause(e.target.value)}><option value="">—</option>{causes.map(key=><option key={key} value={key}>{t(key)}</option>)}</select></label><label><span>{t("resultNote")}</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={t("resultPlaceholder")} maxLength={300}/></label><TechnicianPhotoInput label={t("resultPhoto")} hint={t("technicianPhotoHint")} value={photo} onChange={setPhoto} t={t}/></div>}{selected.status==="acceptance"&&<div className="waiting-acceptance"><CheckCircle size={31}/><strong>{t("statusAcceptance")}</strong><p>{t("handoverSuccess")}</p></div>}</>:<div className="detail-empty"><Wrench size={38}/><strong>{t(section==="available"?"noAvailable":"noMine")}</strong></div>}</section></div></main><PersistentActionBar actions={taskActions} t={t}/><TransferDialog task={tasks.find(task=>task.id===transferTaskId)} tasks={tasks} onTransfer={transfer} onClose={()=>setTransferTaskId("")} t={t}/></>;
}

export function App(){
  const [tasks,setTasks]=useState(readTasks),[role,setRole]=useState(()=>localStorage.getItem("m4-role")||"admin"),[lang,setLang]=useState(()=>localStorage.getItem("m4-lang")||"zh"),[now,setNow]=useState(Date.now()),[updatedAt,setUpdatedAt]=useState(Date.now()),[toast,setToast]=useState("");
  const [sections,setSections]=useState({admin:"exceptions",operator:"report",technician:"available"});
  const [focusTaskId,setFocusTaskId]=useState(""),[menuOpen,setMenuOpen]=useState(false);
  const t=key=>copy[lang]?.[key]||copy.en[key]||key;
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);useEffect(()=>{const serialized=JSON.stringify(tasks);if(localStorage.getItem(STORAGE_KEY)!==serialized)localStorage.setItem(STORAGE_KEY,serialized);setUpdatedAt(Date.now());},[tasks]);useEffect(()=>{const sync=event=>{if(event.key!==STORAGE_KEY||!event.newValue)return;try{const next=JSON.parse(event.newValue);if(Array.isArray(next))setTasks(next);}catch{}};window.addEventListener("storage",sync);return()=>window.removeEventListener("storage",sync);},[]);useEffect(()=>localStorage.setItem("m4-role",role),[role]);useEffect(()=>{localStorage.setItem("m4-lang",lang);document.documentElement.lang=lang==="zh"?"zh-CN":lang==="bm"?"ms":"en";},[lang]);
  const notify=message=>{setToast(message);clearTimeout(window.__m4ToastTimer);window.__m4ToastTimer=setTimeout(()=>setToast(""),3000);};
  const section=sections[role];
  const setSection=next=>setSections(current=>({...current,[role]:next}));
  const alertCount=tasks.filter(task=>getException(task,now)).length;
  const openSearchTask=task=>{setFocusTaskId(task.id);const target=role==="admin"?(task.status==="closed"?"history":getException(task,Date.now())?"exceptions":"live"):role==="operator"?(task.status==="closed"?"history":"current"):(task.status==="closed"?"history":task.status==="reported"?"available":"current");setSections(current=>({...current,[role]:target}));};
  const workerContent=role==="operator"?<OperatorApp tasks={tasks} setTasks={setTasks} now={now} t={t} lang={lang} notify={notify} section={section} setSection={setSection} setLang={setLang} focusTaskId={focusTaskId}/>:<TechnicianApp tasks={tasks} setTasks={setTasks} now={now} updatedAt={updatedAt} t={t} lang={lang} notify={notify} section={section} setSection={setSection} setLang={setLang} focusTaskId={focusTaskId}/>;
  return <div className={`app-shell ${role!=="admin"?"has-action-bar":alertCount>0?"has-admin-action-bar":""}`}><Header role={role} setRole={setRole} lang={lang} setLang={setLang} t={t} tasks={tasks} onSearchNavigate={openSearchTask} onMenuOpen={()=>setMenuOpen(true)} alertCount={alertCount}/><MobileMenu open={menuOpen} role={role} section={section} setSection={setSection} setRole={setRole} onClose={()=>setMenuOpen(false)} t={t} alertCount={alertCount}/>{role==="admin"?<AdminApp tasks={tasks} setTasks={setTasks} now={now} t={t} lang={lang} notify={notify} setLang={setLang} section={section} setSection={setSection} setRole={setRole} focusTaskId={focusTaskId}/>:<div className="role-layout"><PortalSidebar role={role} section={section} setSection={setSection} setRole={setRole} t={t}/><div className="role-main worker-main">{workerContent}</div></div>}{toast&&<div className="toast" role="status"><CheckCircle size={19} weight="fill"/>{toast}</div>}</div>;
}
